more details in rooms
PoliNetworkOrg/PoliFemoBackend pull request #125
Opened 2023-02-26 19:07 UTC by bob27aggiustatutto

2023-02-26 21:14 UTC, francescolf requested changes
Se lo stato è `FREE` non aggiungiamo un nuovo elemento in `occupancies` ogni 15min, e a questo punto eliminiamo anche il campo `text`

2023-02-26 21:46 UTC, bob27aggiustatutto commented
prova ora

2023-02-27 18:21 UTC, francescolf commented
I duplicati sono risolti, ma questa PR rallenta tantissimo l'endpoint rispetto all'implementazione su `dev`. Come limite massimo per un aula non cachata terrei come riferimento 10sec a richiesta.

Un altro problema che ho notato (ma scollegato da questa PR) è che non vengono restituite le aule che hanno come slot libero **solo** la finestra richiesta (esempio: finestra di ricerca 12.15-14.15, non vengono restituite le aule che sono libere esattamente per questa fascia)

2023-02-27 20:43 UTC, bob27aggiustatutto commented
> Come limite massimo per un aula non cachata terrei come riferimento 10sec a richiesta.

il mio pc impiega 6 secondi a calcolare tutta la sede "MIA". Considerando che poi per un'ora intera è fatta, direi che va più che bene così

2023-02-27 20:43 UTC, bob27aggiustatutto commented
> Un altro problema che ho notato (ma scollegato da questa PR) è che non vengono restituite le aule che hanno come slot libero **solo** la finestra richiesta (esempio: finestra di ricerca 12.15-14.15, non vengono restituite le aule che sono libere esattamente per questa fascia)

eh si stiamo togliendo la fascia oraria come parametro influente nella ricerca, lato backend

2023-02-28 14:34 UTC, francescolf approved these changes
Lo proviamo, ma terrò d'occhio le performance

2023-02-28 14:34 UTC, merged