Feature/cu 861m6g73m
PoliNetworkOrg/PoliFemoBackend pull request #97
Opened 2023-01-27 21:08 UTC by frabazz

endpoint dettaglio aula

2023-01-27 21:09 UTC, PoliNetwork-ClickUp commented
Task linked: [CU-861m6g73m Endpoint per dettaglio aula](https://app.clickup.com/t/861m6g73m)

2023-01-28 09:08 UTC, francescolf requested changes
Serve l' indirizzo/coordinate dell'aula

2023-01-28 09:08 UTC, francescolf commented on Source/Controllers/Rooms/RoomDetails.cs
> +[Route("/rooms/details")]
```suggestion
[Route("/rooms/{id:int}")]
```

2023-01-28 09:08 UTC, francescolf commented on Source/Utils/RoomUtil.cs
> +        var properties = new Dictionary<String, String>();
```suggestion
        var properties = new JObject();

```
Sarebbe meglio usare un `JObject`, così possiamo usare altri formati oltre a `<String>:<String>` nel JSON di risposta

2023-01-28 09:08 UTC, francescolf commented on Source/Utils/RoomUtil.cs
> +            properties["prese"] = list.Contains(id) ? "si" : "no";
```suggestion
            properties["prese"] = list.Contains(id) ? true : false
```
La risposta deve essere coerente con quella dell'endpoint delle aule libere, con un boolean qui e tutti i nomi delle proprietà in inglese (es. "Edificio", "Capienza", etc.)

2023-01-28 16:48 UTC, francescolf approved these changes
:+1:

2023-01-28 16:48 UTC, merged